"""Add attachment_original column to Post

Revision ID: 6cd6ebd1bbc6
Revises: af3655a916b5
Create Date: 2025-08-06 18:38:55.585879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd6ebd1bbc6'
down_revision = 'af3655a916b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_original', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('attachment_original')

    # ### end Alembic commands ###
