"""Add attachment column to Post

Revision ID: af3655a916b5
Revises: 4825fc3ac8ce
Create Date: 2025-08-06 17:57:43.590351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3655a916b5'
down_revision = '4825fc3ac8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('attachment')

    # ### end Alembic commands ###
