"""초기화 후 마이그레이션

Revision ID: e439eff61725
Revises: ff6e2f4d8c4c
Create Date: 2025-08-08 11:02:41.247390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e439eff61725'
down_revision = 'ff6e2f4d8c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_master')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_master', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
