"""초기화 후 마이그레이션

Revision ID: ff6e2f4d8c4c
Revises: 6cd6ebd1bbc6
Create Date: 2025-08-06 18:52:00.511052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6e2f4d8c4c'
down_revision = '6cd6ebd1bbc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
